comments/urls.py
from django.conf.urls import url
from . import views
app_name = 'comments'
urlpatterns = [
    url(r'^(?P<article_id>[0-9]+)/comment/$', views.article_comment, name='article_comment'),
]

focus/urls.py
#encoding:utf-8
from django.conf.urls import include,url
from . import views

app_name = "focus"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.log_in, name='login'),
    url(r'^logout/$', views.log_out, name='logout'),
    url(r'^register/$', views.register, name='register'),
    # url(r'^(?P<article_id>[0-9]+)/comment/$', views.comment, name='comment'),   #comments 独立模块下完成
    url(r'^(?P<article_id>[0-9]+)/poll/$', views.get_poll, name='poll'),
    url(r'^(?P<article_id>[0-9]+)/keep/$', views.get_keep, name='keep'),
    url(r'^(?P<article_id>[0-9]+)/$', views.article, name='detail'),
]

urlpatterns += [
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),    #文章归档
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),  #和上一行归档同样的效果
    # url(r'^category/(?P<category_id>[0-9]+)/$', views.CategoryView.as_view(), name='category'),  #文章分类
    url(r'^category/(?P<category_id>[0-9]+)/$', views.category, name='category'),
]

just_cms/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from focus import urls as focus_urls
from comments import urls as comments_urls
from focus import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^focus/', include(focus_urls)),
    url(r'^comments/', include(comments_urls)),
    url(r'^$', views.index, name='index'),
    url(r'', include('ckeditor_uploader.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
# -*- coding: utf-8 -*-
from django.db import models
# from django.utils.six import python_2_unicode_compatible
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
class Comment(models.Model):
    user = models.ForeignKey('focus.NewUser')
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey('focus.Article')

    def __str__(self):
        return self.content[:20]

focus/models.py
# -*- coding: utf-8 -*-
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse

class ArticleManager(models.Manager):
    def query_by_column(self, category_id):
        query = self.get_queryset().filter(category_id=category_id)
    def query_by_user(self, user_id):
        user = User.objects.get(id=user_id)
        article_list = user.article_set.all()
        return article_list
    def query_by_polls(self):
        query = self.get_queryset().order_by('likes')
        return query
    def query_by_time(self):
        query = self.get_queryset().order_by('-create_time')
        return query
    def query_by_keyword(self, keyword):
        query = self.get_queryset().filter(title__contains=keyword)
        return query

@python_2_unicode_compatible
class NewUser(AbstractUser):
    profile = models.CharField('profile', default='', max_length=256)
    def __str__(self):
        return self.username

@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField('类名', max_length=16)
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    intro = models.TextField('introduction', default='')

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Author(models.Model):
    name = models.CharField('姓名', max_length=256)
    profile = models.CharField('简介', default='', max_length=256)
    register_time = models.DateTimeField(auto_now_add=True, editable=True)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField('标签名',  max_length=16)
    create_time = models.DateTimeField('创建时间', auto_now_add=True)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
    )
    title = models.CharField('标题', max_length = 64)
    author = models.ForeignKey(Author, verbose_name='作者', null=True, on_delete=models.SET_NULL)
    # content = models.TextField('正文')
    content = RichTextUploadingField(verbose_name='正文')
    create_time = models.DateTimeField('创建时间', auto_now_add=True)   #文章添加时自动添加创建时间
    last_modified_time = models.DateTimeField('最近编辑时间', auto_now=True)
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES)
    #文章摘要 help_text 在该 field 被渲染成  form 时 显示帮助信息
    abstract = models.CharField('摘要', max_length=54, blank=True, null=True, help_text="可选，如若为空将摘取正文前54个字符")
    # PositiveIntegerField 存储非负整数
    views = models.PositiveIntegerField('浏览量', default=0)
    topped = models.BooleanField('置顶', default=False)
    #on_delete=models.SET_NULL 表示删除category分类后该分类下所有的Article的外键均设为null
    category = models.ForeignKey(Category, verbose_name='分类', null=True, on_delete=models.SET_NULL)
    comment_num = models.PositiveIntegerField('评论数', default=0)
    keep_num = models.PositiveIntegerField('收藏数', default=0)
    like_num = models.PositiveIntegerField('点赞数', default=0)
    tags = models.ManyToManyField(Tag, verbose_name='标签集合', blank=True)

    def __str__(self):
        #主要用于交互解释器显示表示该类的字符串
        return self.title
    def get_absolute_url(self):
        return reverse('focus:detail', kwargs={'article_id': self.id})		#在模板中可以直接调用,获取最新文章

    class Meta:
        # Meta包含一系列选项,此处ordering 表示排序， - 逆序
        ordering = ['-last_modified_time']
    objects = ArticleManager()
    
#comment 在 comments 单独的app下完成
# @python_2_unicode_compatible
# class Comment(models.Model):
#     user = models.ForeignKey(NewUser, null=True)
#     article = models.ForeignKey(Article, null=True)
#     content = models.TextField()
#     create_time = models.DateTimeField(auto_now_add=True, editable=True)
#     poll_num = models.IntegerField(default=0)
#
#     def __str__(self):
#         return self.content

class Poll(models.Model):   #点赞
    user = models.ForeignKey(NewUser, null=True)
    article = models.ForeignKey(Article, null=True)

class Keep(models.Model):   #收藏
    article = models.ForeignKey(Article, null=True)
    user = models.ForeignKey(NewUser, null=True)

focus/forms.py
#encoding:utf-8
from django import forms
import re
from django.core.exceptions import ValidationError

class LoginForm(forms.Form):
    uid = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'id':'uid', 'placeholder': 'Username'}))
    pwd = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'id':'pwd', 'placeholder':'Password'}))

def email_validate(value):
    email_re = re.compile(r'^[0-9a-zA-Z_]{0,19}@[0-9a-zA-Z]{1,13}\.[com,cn,net]{1,3}$')
    if not email_re.match(value):
        raise ValidationError('邮箱格式错误')

class RegisterForm(forms.Form):
    username = forms.CharField(label='username', max_length=100,
        widget=forms.TextInput(attrs={'id':'username', 'onblur':'authentication()','placeholder': 'Username',}),
        error_messages = {'required':'bunennegewf'})
    email = forms.EmailField(validators=[email_validate], error_messages={'required':u'邮箱不能为空'},
        widget=forms.TextInput(attrs={'id':'email', 'placeholder': 'email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'id':'password1', 'placeholder': 'password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'id':'password2', 'placeholder': 'please comfirm password'}))

class SetInfoForm(forms.Form):
    username = forms.CharField()

class CommmentForm(forms.Form):
    comment = forms.CharField(label='', widget=forms.Textarea(attrs={'cols': '60', 'rows': '6'}))

class SearchForm(forms.Form):
    keyword = forms.CharField(widget=forms.TextInput)

focus/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Poll, NewUser,Keep, Tag, Category
from comments.forms import CommentForm
from .forms import CommmentForm, LoginForm, RegisterForm, SetInfoForm
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.views.decorators.cache import cache_page
from django.contrib.auth.hashers import make_password
from django.http  import  HttpResponseRedirect
from django.views.generic import ListView

import markdown, urlparse

def index(request):
    latest_article_list = Article.objects.query_by_time()
    articles_info = []
    dic = {}
    for article in latest_article_list:
        taginfo = Article.objects.get(id=article.id)
        dic['tag_list'] = taginfo.tags.all()
        dic['article'] = article;
        articles_info.append(dic)
        dic = {}

    loginform = LoginForm()
    context = {'articles_info':articles_info, 'loginform':loginform}
    return render(request, 'index.html', context)

def log_in(request):        #注意该处命名不能为login，会重名导致错误
    if request.user.is_authenticated:
        return redirect('/focus')
    if request.method == 'GET':
        form = LoginForm()
        # request.session['login_from'] = request.META.get('HTTP_REFERER', '/')   #记住原来的URL，如果没有则设置为首页('/')
        return render(request, 'login.html', {'form':form})
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['uid']
            password = form.cleaned_data['pwd']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # url = request.POST.get('source_url', '/focus')
                # return redirect(url)
                return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))  #定向到登录之前的url
            else:
                return render(request, 'login.html', {'form':form, 'error':'password or username is not true!'})
        else:
            return render(request, 'login.html', {'form':form})

@login_required
def log_out(request):
    url = request.POST.get('source_url', '/focus')
    logout(request)
    return redirect(url)

# def article(request, article_id):
#     article = get_object_or_404(Article, id=article_id)
#     taginfo = Article.objects.get(id=article_id)  #多对多查询
#     tag_list = taginfo.tags.all()
#
#     #根据标签查询对应文章
#     # articleinfo = Tag.objects.get(id=3)
#     # article_list = articleinfo.article_set.all()
#
#     content = markdown2.markdown(article.content, extras=[
#         "code-friendly",
#         "fenced-code-blocks",
#         "header-ids",
#         "toc",
#         "metadata"
#     ])
#     commentform = CommmentForm()
#     loginform = LoginForm()
#     comments = article.comment_set.all
#
#     return render(request, 'detail.html', {
#         'article':article,
#         'tag_list':tag_list,
#         'loginform':loginform,
#         'commentform':commentform,
#         'content':content,
#         'comments':comments
#     })

def article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    taginfo = Article.objects.get(id=article_id)  #多对多查询
    tag_list = taginfo.tags.all()
    article.content = markdown.markdown(article.content, extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    form = CommmentForm()
    #获取该article所有的comment
    comment_list = article.comment_set.all()
    context = {
        'article':article,
        'form':form,
        'comment_list':comment_list,
        'tag_list':tag_list,
    }
    return render(request, 'detail.html', context)

# @login_required
# def comment(request, article_id):
#     form = CommmentForm(request.POST)
#     url = urlparse.urljoin('/focus/', article_id)
#     if form.is_valid():
#         user = request.user
#         article = Article.objects.get(id=article_id)
#         new_comment = form.cleaned_data['comment']
#         #构造一个评论的对象
#         c = Comment(content=new_comment, article_id=article_id)
#         #查询，此处应该为构造一个新的comment，而这个为从数据库查询，所以此处不合适
#         # c = Comment.objects.get(content=new_comment, article_id=article_id)
#         c.user = user
#         c.save()
#         article.comment_num += 1
#         article.save()
#     return redirect(url)

@login_required
def get_keep(request, article_id):  #收藏 keep
    logged_user = request.user
    article = Article.objects.get(id=article_id)
    is_keep = Keep.objects.filter(article_id=article_id, user_id=logged_user.id)
    if len(is_keep) == 0:  #未收藏，点击收藏
        article.keep_num += 1
        article.save()
        keep = Keep(article=article, user=logged_user)
        keep.save()
    else:           #已收藏，点击取消收藏
        article.keep_num -= 1
        article.save()
        Keep.objects.get(article_id=article_id, user_id=logged_user.id).delete()
    url = urlparse.urljoin('/focus/', article_id)
    return redirect(url)



@login_required
def get_poll(request, article_id):  #点赞 poll
    logged_user = request.user
    article = Article.objects.get(id=article_id)
    is_poll = Poll.objects.filter(article_id=article_id, user_id=logged_user.id)
    if len(is_poll) == 0:  #未收藏，点击收藏
        article.like_num += 1
        article.save()
        poll = Poll(article=article, user=logged_user)
        poll.save()
    else:           #已收藏，点击取消收藏
        article.like_num -= 1
        article.save()
        Poll.objects.get(article_id=article_id, user_id=logged_user.id).delete()
    url = urlparse.urljoin('/focus/', article_id)
    return redirect(url)

def register(request):
    error1 = "the name is already exist"
    valid = "this name is valid"
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'register.html', {'form':form})
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if request.POST.get('raw_username', 'erjgiqfv240hqp5668ej23foi') != 'erjgiqfv240hqp5668ej23foi':
            try:
                user = NewUser.objects.get(username=request.POST.get('raw_username', ''))
            except ObjectDoesNotExist:
                return render(request, 'register.html', {'form':form, 'msg':valid})
            else:
                return render(request, 'register.html', {'form':form, 'msg':error1})
        else:
            if form.is_valid():
                username = form.cleaned_data['username']
                email = form.cleaned_data['email']
                password1 = form.cleaned_data['password1']
                password2 = form.cleaned_data['password2']
                if password1 != password2:
                    return render(request, 'register.html', {'form':form, 'msg':'Do not match the password input'})
                else:
                    password = make_password(password2, None, "pbkdf2_sha256")
                    user = NewUser(username=username, email=email, password=password)
                    user.save()
                    # return render(request, 'login.html', {'success':'you have successfully registered!'})
                    return redirect('/focus/login')
            else:
                return render(request, 'register.html', {'form':form, 'msg':'input msg is invalid!'})

class ArchivesView(ListView):   #文章归档
    model = Article
    template_name = 'index.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(create_time__year=year,
                                                               create_time__month=month
                                                               )

class CategoryView(ListView):   #文章分类
    model = Article
    template_name = 'index.html'
    context_object_name = 'categories_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, id=self.kwargs.get('category_id'))
        return super(CategoryView, self).get_queryset().filter(category=cate)

def archives(request, year, month):
    article_list = Article.objects.filter(create_time__year=year, create_time__month=month).order_by('-create_time')
    articles_info = []
    dic = {}
    for article in article_list:
        taginfo = Article.objects.get(id=article.id)
        dic['tag_list'] = taginfo.tags.all()
        dic['article'] = article;
        articles_info.append(dic)
        dic = {}

    loginform = LoginForm()
    context = {'articles_info':articles_info, 'loginform':loginform}
    return render(request, 'index.html', context)

def category(request, category_id):
    cate = get_object_or_404(Category, id=category_id)
    article_list = Article.objects.filter(category=cate).order_by('-create_time')
    articles_info = []
    dic = {}
    for article in article_list:
        taginfo = Article.objects.get(id=article.id)
        dic['tag_list'] = taginfo.tags.all()
        dic['article'] = article;
        articles_info.append(dic)
        dic = {}

    loginform = LoginForm()
    context = {'articles_info':articles_info, 'loginform':loginform}
    return render(request, 'index.html', context)

focus/templates/article_base.html
{% load staticfiles %}
{% load articleinfo %}
<!DOCTYPE html>
<!-- Template by Quackit.com -->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>JUST - CMS</title>
    <link rel="icon" href="{% static 'images/apple.ico' type="image/x-icon" %}"/>
    <script src="{% static "js/csrf.js" %}"></script>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/pygments.css" %}" rel="stylesheet">
    <link href="{% static "css/custom.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-globe"></span> Logo</a>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Products</a>
                    </li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Services <span class="caret"></span></a>
						<ul class="dropdown-menu" aria-labelledby="about-us">
							<li><a href="#">Engage</a></li>
							<li><a href="#">Pontificate</a></li>
							<li><a href="#">Synergize</a></li>
						</ul>
					</li>
                </ul>

				<!-- Search -->
				<form class="navbar-form navbar-right" role="search">
					<div class="form-group">
						<input type="text" class="form-control">
					</div>
					<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Search</button>
				</form>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

	<div class="container-fluid">

		<!-- Left Column -->
		{% block left %}
		{% endblock left %}
		<!--/Left Column-->

		<!-- Center Column -->
		{% block center %}
		{% endblock center %}
		<!--/Center Column-->

		<!-- Right Column -->
		<div class="col-sm-3">
		{% if request.user.is_authenticated %}
			<!-- Form -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-user"></span>
                        Logged In
                    </h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">hi:{{ user }} <a href="/focus/logout/"><input class="btn btn-default" type="submit" value="Logout" /></a></div>
                </div>
            </div>
            {% else %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-log-in"></span>
                        Log In
                    </h3>
                </div>
                <div class="panel-body">
                    <form action="{% url 'focus:login' %}" method="post">
                        {% csrf_token %}
                        {{ loginform.non_field_errors }}
                        <div class="form-group">
                            {{ loginform.uid }}
                        <!-- <input type="text" class="form-control" id="uid" name="uid" placeholder="Username">  -->
                        </div>
                        <div class="form-group">
                            {{ loginform.pwd }}
                        <!-- <input type="password" class="form-control" id="pwd" name="pwd" placeholder="Password">  -->
                        </div>
                        <button type="submit" class="btn btn-default">Log In</button>
                    </form>
                </div>
            </div>
            {% endif %}

			<!-- last recent articles -->
            <div class="widget widget-recent-posts">
                <h3 class="widget-title">最新文章</h3>
                {% get_recent_articles as recent_articles_list %}
                <ul>
                    {% for article in recent_articles_list %}
                        <li>
                            <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                        </li>
                    {% empty %}
                        暂无文章！
                    {% endfor %}
                </ul>
            </div>

			<!-- archivew -->
            <div class="widget widget-archives">
                <h3 class="widget-title">归档</h3>
                {% archives as date_list %}
                <ul>
                 {% for date in date_list %}
                     <li>
                         <a href="{% url 'focus:archives' date.year date.month %}">{{ date.year }}
                             年 {{ date.month }} 月</a>
                     </li>
                 {% empty %}
                     暂无归档！
                 {% endfor %}
                </ul>
            </div>

            <!--category-->
            <div class="widget widget-category">
                <h3 class="widget-title">分类</h3>
                {% get_categories as category_list %}
                <ul>
                    {% for category in category_list %}
                        <li>
                            <a href="{% url 'focus:category' category.pk %}">{{ category.name }} <span
                                    class="post-count">({{ category.num_posts }})</span></a>
                        </li>
                    {% empty %}
                        暂无分类！
                    {% endfor %}
                </ul>
            </div>

		</div><!--/Right Column -->
	</div><!--/container-fluid-->

	<footer>
		<div class="footer-blurb">
			<div class="container">
				<div class="row">
					<div class="col-sm-3 footer-blurb-item">
						<h3><span class="glyphicon glyphicon-text-size"></span> Dynamic</h3>
						<p>Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.</p>
						<p><a class="btn btn-default" href="#">Procrastinate</a></p>
					</div>
					<div class="col-sm-3 footer-blurb-item">
						<h3><span class="glyphicon glyphicon-wrench"></span> Efficient</h3>
						<p>Dramatically maintain clicks-and-mortar solutions without functional solutions. Efficiently unleash cross-media information without cross-media value. Quickly maximize timely deliverables for real-time schemas. </p>
						<p><a class="btn btn-default" href="#">Unleash</a></p>
					</div>
					<div class="col-sm-3 footer-blurb-item">
						<h3><span class="glyphicon glyphicon-paperclip"></span> Complete</h3>
						<p>Professionally cultivate one-to-one customer service with robust ideas. Completely synergize resource taxing relationships via premier niche markets. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
						<p><a class="btn btn-default" href="#">Complete</a></p>
					</div>
					<div class="col-sm-3 footer-blurb-item">

						<!-- Thumbnails -->
						<h3><span class="glyphicon glyphicon-camera"></span> Phosfluorescent</h3>
							<div class="row">
								<div class="col-xs-6">
									<a href="#" class="thumbnail">
										<img src="holder.js/110x80" alt="">
									</a>
								</div>
								<div class="col-xs-6">
									<a href="#" class="thumbnail">
										<img src="holder.js/110x80" alt="">
									</a>
								</div>
								<div class="col-xs-6">
									<a href="#" class="thumbnail">
										<img src="holder.js/110x80" alt="">
									</a>
								</div>
								<div class="col-xs-6">
									<a href="#" class="thumbnail">
										<img src="holder.js/110x80" alt="">
									</a>
								</div>
							</div>

					</div>

				</div>
				<!-- /.row -->
			</div>
        </div>

        <div class="small-print">
        	<div class="container">
        		<p><a href="#">Terms &amp; Conditions</a> | <a href="#">Privacy Policy</a> | <a href="#">Contact</a></p>
        		<p>Copyright &copy; Example.com 2015 </p>
        	</div>
        </div>
	</footer>


    <!-- jQuery -->
    <script src="{% static "js/jquery-1.11.3.min.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

	<!-- IE10 viewport bug workaround -->
	<script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>

	<!-- Placeholder Images -->
	<script src="{% static "js/holder.min.js" %}"></script>

</body>

</html>

focus/templates/login.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>登录 - CMS-首页</title>
	<meta name="keywords" content="XICMS">
	<meta name="content" content="XICMS">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
	{% load staticfiles %}
	<link rel="icon" href="{% static 'images/apple.ico' type="image/x-icon" %}"/>
    <link type="text/css" rel="stylesheet" href="{% static "css/login.css" %}">
    <script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
</head>
<body class="login_bj" >
<div class="zhuce_body">
    <div class="zhuce_kong login_kuang">
    	<div class="zc">
        	<div class="bj_bai">
            <h3>登录</h3>
	   	  		<form action="" method="post">
					{% csrf_token %}
					{% for field in form %}
						{{ field.lable_tag }}
						{{ field }}
					{% endfor %}
	                <div>
	               		<a href="#">忘记密码？</a><input name="" type="checkbox" value="" checked><span>记住我</span>
	                </div>
	                <input name="登录" type="submit" class="btn_zhuce" value="登录">
	        	</form>
            </div>
        	<div class="bj_right">
            	<p>使用以下账号直接登录</p>
                <a href="#" class="zhuce_qq">QQ登录</a>
                <a href="#" class="zhuce_wb">微博登录</a>
                <a href="#" class="zhuce_wx">微信登录</a>
                <p>还没账号？<a href="../register">立即注册</a></p>

            </div>
        </div>
        <P>www.justbreaking.com&nbsp;©&nbsp;版权所有</P>
    </div>

</div>

</body>
</html>

focus/templates/login_01.html
<!doctype html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CMS - 登录</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
</head>
<body>
<div class="wrap">
	<div class="wrapper">
		<div class="container">
			<h1>Welcome</h1>
			<form action="" method="post">
				{% csrf_token %}
				{% for field in form %}
					{{ field.lable_tag }}
					{{ field }}
				{% endfor %}
				<input type="submit" value="登录" />
			</form>
		</div>
	</div>
</div>

<div style="text-align:center;margin:50px 0; font:normal 14px/24px 'MicroSoft YaHei';color:#000000">
<h1>CMS系统登录</h1>
</div>
</body>
</html>